#!/usr/bin/env python3
from argparse import ArgumentParser
import sys


p = ArgumentParser()
p.add_argument('--difftool', default='vimdiff')
p.add_argument('--diff', action='store_const', dest='difftool', const='diff')
p.add_argument('--extract', '-e', action='store_true')
p.add_argument('first')
p.add_argument('second')
args = p.parse_args()
F = args.first
S = args.second

from subprocess import check_call, run


uu = '--extract' if args.extract else ''
res = run([
    'bash',
    '-c',
    # hack to propagate failures in process substitution https://unix.stackexchange.com/a/217643/180307
    f'{args.difftool} <(./normalise {uu} "{F}" || kill $$) <(./normalise {uu} "{S}" || kill $$)',
])


assert res.returncode <= 1
sys.exit(res.returncode)
