#!/bin/bash -eu

cd "$(dirname "$0")"
cd ..

if ! command -v sudo; then
    # CI or Docker sometimes don't have it, so useful to have a dummy
    function sudo {
        "$@"
    }
fi

if ! [ -z "$CI" ]; then
    # install OS specific stuff here
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macos
        brew install jq
    else
        sudo apt update
        sudo apt install jq
    fi
fi

pip3 install --user tox
tox
